### ISSUE TITLE
Why ExoScrapers?

### ISSUE THREAD

**Issue by reddit-reaper** [kodibae/repository.kodibae#1]
So i saw that you forked OpenScrapers, not really a big deal and idc really, but why create a whole other module for if its the same thing? you could just send PRs to OpenScrapers and use OpenScrapers in your addon instead. would be better for the community as a whole to have more people contributing to one project instead of making multiple separate ones imho. Just my thoughts on this is all.

**Comment by kodibae** [comment]
Rather not link to an outside group, no offence.
