### ISSUE TITLE
Browse for Subtitles crashes the app

### ISSUE THREAD

**Issue by htatla81** [kodibae/repository.kodibae#10]
Exodus latest version. 
When playing a stream and opening :
Subtitles > Browse for subtitle...

The app freezes and eventually crashes 

Hardware: Amazon Fire stick 2nd gen

**Comment by kodibae** [comment]
Pls provide log @htatla81

**Comment by htatla81** [comment]
Please see attached at Around 20:40 time stamp

[kodi.log](https://github.com/kodibae/repository.kodibae/files/3980619/kodi.log)

**Comment by htatla81** [comment]
any update ?
