### ISSUE TITLE
It's not working now

### ISSUE THREAD

**Issue by Greathouse2005** [kodibae/repository.kodibae#2]
I've trioed everything including the vpn crap... I can not get any good hd sources now... and nothing plays... stuff I've previously watched doesn't work now either. what gives? and it won't let me use an older version that I know works.  Why?

**Comment by kodibae** [comment]
Openload & streamango shut down, short term issue.

**Comment by Greathouse2005** [comment]
it's not those... It's the seriesonline and the vidnode never works.
