### ISSUE TITLE
exodus module 2.3.5  update on july 6th(in Europe) does NOT work ! Nothing works !

### ISSUE THREAD

**Issue by eeden003** [kodibae/repository.kodibae#20]
exodus module 2.3.5  update on july 6th(in Europe) does NOT work ! Nothing works !

When wanting to adjust scrapers-settings, an exodus-module error appears.
When clicking on a movie or series, an exodus-module error appears.
Have tested more choices in the menu, but I gave up, an exodus-module error appears.

This happens on 2 different KodiBoxes with different Android-versions and different Kodi-versions(19.X)
This also happens on PC Windows 7with newest Kodi !

**Comment by htatla81** [comment]
Having same issue on 6th July update - Error on attempting to Pick/scrape content 

Errors I see in the log : 

Metahandler module (MetaHandlers version: 3.99.02) cannot find module called “exoscrapers”

Perhaps a simple file name error or typo to connect the new updates to scraper? (As mentioned on 6th July startup message from kodibae)

**Comment by htatla81** [comment]
My log uploaded :

**Comment by eeden003** [comment]
just recieved TWO new updates for Exodus, it works again, thanks !
