### ISSUE TITLE
Providers settings issue 

### ISSUE THREAD

**Issue by htatla81** [kodibae/repository.kodibae#28]
V10.00

On “Providers” section in settings - “Play scrapers” option is duplicated in error and appears twice on the menu (shortcut options appear as “Open Play Scrapers Settings” and then again as “Open Playscrapers Settings”)

I believe the second option was intended to be “Exo Scrapers Settings” which is missing 

The “Provider Source:” profile is labelled “Play Scrapers, Play Scrapers” which I believe was intended to be “Play Scrapers + Exo Scrapers” which is a missing choice/combination

![image](https://user-images.githubusercontent.com/55095730/98471392-c321d800-21e3-11eb-8fd5-064fb12cadde.jpg)

![image](https://user-images.githubusercontent.com/55095730/98471413-e8aee180-21e3-11eb-98cd-e40f45b5bf3a.jpg)

**Comment by kodibae** [comment]
will fix in next update, going with play scrapers solely though
