### ISSUE TITLE
This is now a clone

### ISSUE THREAD

**Issue by host505** [kodibae/repository.kodibae#29]
...of my add-on theoath, and you also host in your repo another clone off it (pressplay).
Both of these add-ons have removed any sign of previous contributors credits, and are even still using my hardcoded API keys.
Hell you even have some artwork of my add-on in it lol (see #27)
That's the most f'd up shit i've ever seen in this scene that i've been around for over 10 years.
Now you fakes/cloners good luck fixing TV shows when tvdb API goes paid soon - I've already a working tvdb free version, but I won't be publicizing it after this, for you fakes to sell VPN.

**Comment by htatla81** [comment]
@kodibae is this true? What gives? Neither The play scrapers nor Exo currently work and my logs mention tvdb API key issue 
Is this the end?!

**Comment by kodibae** [comment]
the latest update should have fixed it, this guy's "fork" is a clone in the first place - lmk @htatla81

**Comment by htatla81** [comment]
I still love your work. I hope my feedback helps
