### ISSUE TITLE
Xxx o dus

### ISSUE THREAD

**Issue by deanogers** [kodibae/repository.kodibae#3]
Hi just wondering if you are going to fix this addon as nothing works on it thanks none of the videos work

**Comment by dyolflaen** [comment]
Watchxxxfree hasn't been working for months.

**Comment by bigsgtj** [comment]
Need code

**Comment by eeden003** [comment]
Note: when using ONLY the repo from kodibae, XXXoDus still keeps working ! DO NOT use any of the updates when available, including TVADDONS, because the app stops working completely and will not start ! This is what happens on my equipment with Kodi and apps.
