### ISSUE TITLE
Nothing is working i watched a show and now not 5 minutes later i can't watch anything. there are zero sources

### ISSUE THREAD

**Issue by Greathouse2005** [kodibae/repository.kodibae#30]
Nothing is working i watched a show and now not 5 minutes later i can't watch anything. there are zero sources

**Comment by kodibae** [comment]
make sure you have the latest release, provide error log if still broken @Greathouse2005

**Comment by Greathouse2005** [comment]
I can't find the log... there hasn't been an error show up so not sure what to do but I was able to watch on a different device and i guess at some point in the night it updated to and now it doesn't work.

**Comment by Greathouse2005** [comment]
okay weird... it's working again... but not working... it's like intermittent. it's lioke a 50 50 shot whether it will find source or not...
