### ISSUE TITLE
"Invalid Structure"

### ISSUE THREAD

**Issue by HappyZombieSlayer** [kodibae/repository.kodibae#38]
I am trying to set up Kodi on my HP Envy, windows 10 PC. I have set it up before multiple times on the raspberry pi -- every version has been Kodi 18.9. I generally install Netflix, Disney+, Amazon VOD, and Exodus V8. I have successfully installed each repository except for Kodi Bae. Every time I  try to do it, it replies the the addon installation has failed due to an "invalid structure." Is this a conflict with my PC? I have the same issue if I go back to version "repository.kodibae-3.0.0.zip"

**Comment by vspin** [comment]
I'm getting the same error response installing on Firestick with Kodi Matrix.

**Comment by Mikesco3** [comment]
Getting the same Error on Kodi build 19.1 (19.1.0)

**Comment by boliiih** [comment]
same as can't install on matrix 19.1

**Comment by kodibae** [comment]
Fixed
