### ISSUE TITLE
TVShows\Search is broken since Nov14th update

### ISSUE THREAD

**Issue by The-NinthWave** [kodibae/repository.kodibae#5]
The update that was pushed on Nov 14th came with some dependencies or script that broke the search results in TV Shows.

Those dependencies are common with Exodus Redux since the TV Shows search function is broke as well and there was no update made to this addon itself.

This behavior is seen in my 3 Android boxes as well as Windows

**Comment by dobbelina** [comment]
The TVDB scraper is currently broken due to upgrade works at TheTVDB site.
https://www.reddit.com/r/Addons4Kodi/comments/dwip1v/tvdb_is_undergoing_maintenance_expect_addon/

**Comment by dobbelina** [comment]
Partial fix,still problem with thumbnails:
script.module.exodus\lib\resources\lib\indexers\episodes.py
Change **%s.xml** to **%s.zip.xml** (5 instances)
And:
script.module.exodus\lib\resources\lib\indexers\tvshows.py
Change **%s.xml** **%s.zip.xml** (1 instances)

https://www.reddit.com/r/Addons4Kodi/comments/dx6396/exodus_forks_and_tvdb_a_possible_fix/

**Comment by kodibae** [comment]
👍👍👍 @dobbelina
