### ISSUE TITLE
How to contribute to exodus

### ISSUE THREAD

**Issue by melvsparks** [kodibae/repository.kodibae#7]
I would like to know where the source code lives for exodus so I can contribute to the addon.

**Comment by kodibae** [comment]
Scrapers: https://github.com/kodibae/repository.kodibae/tree/master/script.module.exoscrapers
Addon: https://github.com/kodibae/repository.kodibae/tree/master/plugin.video.exodus

Email me @melvsparks : kodibae@openmail.cc

**Comment by melvsparks** [comment]
Thanks so much! You're doing a great job maintaining the app
