### ISSUE TITLE
Exodus version 6.0.0 freezes when searching for movies

### ISSUE THREAD

**Issue by eeden003** [kodibae/repository.kodibae#7]
Hello ! First of all, great job, this update gives me 100-200 links of my favourite series. One small issue however: when using MOVIES (cinema and/or new) the addon gives a nice list of movies. When selecting a movie the search starts searching but after a few moments the add-on freezes. Clicking on CANCEL has also no effect. When DE-Activating DIVXCRAWLER  inside your add-on everything works perfectly again !.Keep on doing your good work !

**Comment by leeuwtjex** [comment]
Thanks man!  This piece of info was impossible to find anywhere. Only a lot of useless stuff. You are the 1 million Dollar man for me today! Only I don't have a million Dollar....Just a big THANK YOU!!!

**Comment by ThomasDevOps** [comment]
my Exodus was also freezing, doing this fixed it thanks !!!

to clarify go to Exodus >> Tools >> General settings >> Sources >> disable DIVXCRAWLER  (so it wont search that one)

good luck !
